# Default settings from https://prometheus.io/docs/prometheus/latest/getting_started/
global:
  scrape_interval:     15s 
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']